name = "stm32_gui"
description = "stm32 Graphical User Interface (GUI) utilities"
version = "0.1.0"
licenses = "BSD-3-Clause"

authors = ["AdaCore"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]
website="https://github.com/GNAT-Academic-Program/stm32_gui"
tags = ["embedded", "stm32", "gui"]

[[depends-on]]
stm32_hal = "0.1.0"
adl_middleware = "0.2.0"

[configuration.values]
#cortex_m.core = "m4f"